export interface Product {
    id?:number,
    Availability: number,
    Brands: { id: number, BrandCode: string, BrandName: string, CreatedAt: string, UpdatedAt: string },
    BrandKey: number,
    CreatedAt: string,
    Description: string,
    IsInCart: number,
    IsInWishlist: number,
    IsNewSeason: number,
    IsOnOffer: number,
    IsPopular: number,
    IsTrending: number,
    MaxRating: number,
    Name: string,
    OfferPrice: number,
    Price: number,
    ProductCondition: string,
    ProductID: string,
    ProductImageUrl: string,
    ProductsSubTypeKey: number,
    Rating: number,
    UpdatedAt: string,
}